# lec6.2, 9 Feb 2023

In [1]:
#numpy stuff
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt

A recommender system motivation for dot products in linear algebra.

Imagine users and movies characterized by three integer features ranging from -3 to 3

In [2]:
user0 = np.random.randint(-3,4,3)
movie0 = np.random.randint(-3,4,3)

user0, movie0

(array([ 3, -3, -2]), array([1, 2, 1]))

The features could correspond to the predilection of the user for, say, romance, comedy, and action; and the corresponding feature for the movie could be some measure of how much of that feature it contains. So a user that is neutral about romance, loves comedy, and hates action might be characterized by (0, 3, -3); and an action movie with some amount of romance and comedy might be characterized by (1, 1, 3). In this naive picture, the extent to which a user might like a movie is given by multiplying the associated weights and summing, providing the largest positive contribution when a user strongly likes a feature that the movie contains a lot of (or doesn't like a feature that the movie doesn't contain).

In [3]:
user0[0]*movie0[0] + user0[1]*movie0[1] + user0[2]*movie0[2]

-5

In [4]:
#or equivalently
s=0
for i in range(3):
    s+= user0[i]*movie0[i]
s

-5

In linear algebra, these arrays of numbers are called *vectors*,<br>
and the operation of multiplying the corresponding weights and taking the sum
is called the *dot product*.<br>
It is supported as a method for numpy arrays:

In [5]:
user0 @ movie0

-5

In [6]:
#now consider 10 such users
users = np.random.randint(-3,4,(10,3))
users

array([[ 2,  0, -1],
       [-3,  3,  0],
       [-1, -3,  2],
       [ 2,  1, -2],
       [ 2, -1, -3],
       [ 0, -1,  2],
       [-3,  0,  2],
       [-2, -2, -1],
       [-3, -1,  0],
       [ 3,  3, -2]])

In [7]:
#and see how much each such user would be predicted to like movie0
print ('user features ', 'affinity score with movie', movie0)
for user in users: print (user, '\t', user.dot(movie0))

user features  affinity score with movie [1 2 1]
[ 2  0 -1] 	 1
[-3  3  0] 	 3
[-1 -3  2] 	 -5
[ 2  1 -2] 	 2
[ 2 -1 -3] 	 -3
[ 0 -1  2] 	 0
[-3  0  2] 	 -1
[-2 -2 -1] 	 -7
[-3 -1  0] 	 -5
[ 3  3 -2] 	 7


In [8]:
#these scores can be calculated with a single dot product
# of the list of all ten 10 users with the movie
users @ movie0

array([ 1,  3, -5,  2, -3,  0, -1, -7, -5,  7])

In [9]:
#now consider a list of 5 movies:
movies = np.random.randint(-3,4,(5,3))
movies

array([[ 2,  3, -2],
       [-3, -2,  2],
       [ 2,  3,  1],
       [-1,  1,  0],
       [-1,  3, -3]])

In [10]:
#in this case, the affinity of the i'th user for the j'th movie, say
i=1
j=2
# is given by
print (users[i], '.', movies[j], '=', users[i] @ movies[j])

[-3  3  0] . [2 3 1] = 3


In [11]:
#we could calculate these one by one, where the i'th row corresponds
# to the i'th user, and the j'th entry within that row corresponds to the
# j'th movie:
for i in range(10):
    for j in range(5):
        print ('{:5d}'.format(users[i] @ movies[j]), end='')
    print()

    6   -8    3   -2    1
    3    3    3    6   12
  -15   13   -9   -2  -14
   11  -12    5   -1    7
    7  -10   -2   -3    4
   -7    6   -1   -1   -9
  -10   13   -4    3   -3
   -8    8  -11    0   -1
   -9   11   -9    2    0
   19  -19   13    0   12


In [12]:
#but this can also be calculated in a single step
users @ movies.T 

array([[  6,  -8,   3,  -2,   1],
       [  3,   3,   3,   6,  12],
       [-15,  13,  -9,  -2, -14],
       [ 11, -12,   5,  -1,   7],
       [  7, -10,  -2,  -3,   4],
       [ -7,   6,  -1,  -1,  -9],
       [-10,  13,  -4,   3,  -3],
       [ -8,   8, -11,   0,  -1],
       [ -9,  11,  -9,   2,   0],
       [ 19, -19,  13,   0,  12]])

In [13]:
# the .T "transposes" the list of entries
# from five rows of three elements to three rows of five elements
#(compare with five cells above):
movies.T

array([[ 2, -3,  2, -1, -1],
       [ 3, -2,  3,  1,  3],
       [-2,  2,  1,  0, -3]])

In linear algebra, a list of $m$ rows of numbers and $n$ columns is called an $m\times n$ matrix.

`users.dot(movies.T)` above corresponds to the product of a $10\times 3$ matrix with a $3\times 5$ matrix.<br>
(In equations $(UM^T)_{ij} = \sum_{k=0,1,2} U_{ik}M_{jk}$, where the sum is over the three features in this case.)

Here is another example. Note that any entry is given by the dot product (sum of products of weights) of the associated row of the first matrix at left with the corresponding column of the second matrix at above right.

$\hskip1.4in\pmatrix{
\ 3&2&1 &2&2\cr
\ -2       &-3   &-2 &0      &0\cr
\ 2       &3    &0  &-3     &-3\cr}$<br>
$\pmatrix{3&0&3\cr
3&3&-1\cr
2&0&-3\cr
3&2&-3\cr
0&-1&0\cr
2&2&-1\cr
1&2&-3\cr
0&2&-3\cr
-1&2&-3\cr
-3&0&2\cr}\ $
$\pmatrix{15&15&3&-3&-3\cr
1&-6&-3&9&9\cr
0&-5&2&13&13\cr
-1&-9&-1&15&15\cr
2&3&2&0&0\cr
0&-5&-2&7&7\cr
-7&-13&-3&11&11\cr
-10&-15&-4&9&9\cr
-13&-17&-5&7&7\cr
-5&0&-3&-12&-12\cr}$

The numpy built-in dot products are much more efficient than running loops in the python interpreter because they are precompiled functions. For example consider the dot product of two vectors (numpy arrays) of size 1 million entries:

In [14]:
v = np.random.rand(1000000)
w = np.random.rand(1000000)

The two methods give the same result:

In [15]:
s=0
for i in range(1000000):
    s += v[i]*w[i]

print (s, v @ w)

249846.34129215166 249846.34129214459


But the numpy version is more than 400 times faster:

In [16]:
%%timeit
s=0
for i in range(1000000):
    s += v[i]*w[i]

245 ms ± 3.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [17]:
%%timeit
s = v @ w

403 µs ± 12.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


(less than a millisecond compared to roughly 400 milliseconds)

So a calculation that takes 10 seconds using the numpy constructs would take over an hour in a python interpreter loop.

In [18]:
#a non-numpy example
k = np.random.randint(1000000, size=1000000)
k = list(k)
sk = set(k)

In [19]:
%%timeit
123456 in k
#amount of time to test inclusion in a list (linear in size of list)

2.62 ms ± 8.52 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [20]:
%%timeit
123456 in sk
#amount of time to test inclusion in a set (now logarithmic in size)

121 ns ± 1.17 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
